import 'package:flutter/material.dart';

class Mood {
  final String id;
  final String name;
  final String arabicName;
  final IconData icon;
  final Color primaryColor;
  final Color lightColor;
  final Color darkColor;
  final Color accentColor;
  final String description;
  final List<String> quotes;
  final List<String> arabicQuotes;
  final List<String> banglaQuotes;

  const Mood({
    required this.id,
    required this.name,
    required this.arabicName,
    required this.icon,
    required this.primaryColor,
    required this.lightColor,
    required this.darkColor,
    required this.accentColor,
    required this.description,
    required this.quotes,
    required this.arabicQuotes,
    required this.banglaQuotes,
  });

  static const List<Mood> allMoods = [
    Mood(
      id: 'sad',
      name: 'Sad',
      arabicName: 'حزين',
      icon: Icons.sentiment_very_dissatisfied,
      primaryColor: Color(0xFF1565C0),
      lightColor: Color(0xFF42A5F5),
      darkColor: Color(0xFF0D47A1),
      accentColor: Color(0xFF64B5F6),
      description: 'When your heart feels heavy',
      quotes: [
        'And whoever relies upon Allah - then He is sufficient for him. Indeed, Allah will accomplish His purpose.',
        'So remember Me; I will remember you. And be grateful to Me and do not deny Me.',
        'And it is He who created the heavens and earth in truth. And the day He says, "Be," and it is, His word is the truth.',
        'Indeed, with hardship comes ease.',
        'Allah does not burden a soul beyond that it can bear.',
      ],
      arabicQuotes: [
        'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ',
        'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
        'وَهُوَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِالْحَقِّ ۖ وَيَوْمَ يَقُولُ كُن فَيَكُونُ ۚ قَوْلُهُ الْحَقُّ',
        'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
        'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
      ],
      banglaQuotes: [
        'যে আল্লাহর উপর ভরসা করে, তার জন্য আল্লাহই যথেষ্ট। নিশ্চয় আল্লাহ তাঁর কাজ সম্পন্ন করবেন।',
        'সুতরাং তুমি আমাকে স্মরণ কর, আমিও তোমাকে স্মরণ করব। আমার কৃতজ্ঞতা প্রকাশ কর এবং আমার সাথে কুফরি করো না।',
        'তিনিই আকাশ ও পৃথিবী সত্যসহ সৃষ্টি করেছেন। যেদিন তিনি বলবেন "হও" তখনই তা হয়ে যাবে। তাঁর কথাই সত্য।',
        'নিশ্চয় কষ্টের সাথে রয়েছে সুখ।',
        'আল্লাহ কোন ব্যক্তির উপর তার সাধ্যাতীত কোন দায়িত্ব চাপিয়ে দেন না।',
      ],
    ),
    Mood(
      id: 'angry',
      name: 'Angry',
      arabicName: 'غاضب',
      icon: Icons.local_fire_department,
      primaryColor: Color(0xFFD32F2F),
      lightColor: Color(0xFFEF5350),
      darkColor: Color(0xFFB71C1C),
      accentColor: Color(0xFFFF5722),
      description: 'When anger fills your soul',
      quotes: [
        'And whoever forgives and makes reconciliation, his reward is with Allah.',
        'The strong person is not the one who can wrestle someone else down. The strong person is the one who can control himself when he is angry.',
        'Whoever suppresses his anger when he is able to give vent to it, Allah will call him before all of creation.',
        'And the recompense for an evil is an evil like thereof; but whoever forgives and makes reconciliation, his reward is with Allah.',
        'Seek refuge in Allah from Satan when you feel angry.',
      ],
      arabicQuotes: [
        'وَمَن عَفَا وَأَصْلَحَ فَأَجْرُهُ عَلَى اللَّهِ',
        'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',
        'مَنْ كَظَمَ غَيْظًا وَهُوَ قَادِرٌ عَلَى أَنْ يُنْفِذَهُ دَعَاهُ اللَّهُ عَلَى رُءُوسِ الْخَلَائِقِ',
        'وَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِّثْلُهَا ۖ فَمَنْ عَفَا وَأَصْلَحَ فَأَجْرُهُ عَلَى اللَّهِ',
        'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
      ],
      banglaQuotes: [
        'যে ক্ষমা করে ও শান্তি স্থাপন করে, তার পুরস্কার আল্লাহর কাছে রয়েছে।',
        'শক্তিশালী সে নয় যে অন্যকে কুস্তিতে হারায়, বরং শক্তিশালী সে যে রাগের সময় নিজেকে নিয়ন্ত্রণ করতে পারে।',
        'যে ব্যক্তি সক্ষম হওয়া সত্ত্বেও রাগ দমন করে, আল্লাহ তাকে সৃষ্টিকুলের সামনে ডাকবেন।',
        'মন্দের প্রতিদান অনুরূপ মন্দ; কিন্তু যে ক্ষমা করে ও শান্তি স্থাপন করে, তার পুরস্কার আল্লাহর কাছে।',
        'আমি শয়তান থেকে আল্লাহর আশ্রয় প্রার্থনা করি।',
      ],
    ),
    Mood(
      id: 'depressed',
      name: 'Depressed',
      arabicName: 'مكتئب',
      icon: Icons.cloud,
      primaryColor: Color(0xFF424242),
      lightColor: Color(0xFF757575),
      darkColor: Color(0xFF212121),
      accentColor: Color(0xFF9E9E9E),
      description: 'When darkness surrounds you',
      quotes: [
        'And give good tidings to the patient, Who, when disaster strikes them, say, "Indeed we belong to Allah, and indeed to Him we will return."',
        'Allah does not burden a soul beyond that it can bear.',
        'And whoever fears Allah - He will make for him a way out.',
        'No fatigue, nor disease, nor sorrow, nor sadness, nor hurt befalls a Muslim except that Allah expiates some of his sins.',
        'And it is He who sends down rain after [people] have despaired and spreads His mercy.',
      ],
      arabicQuotes: [
        'وَبَشِّرِ الصَّابِرِينَ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
        'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
        'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا',
        'لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
        'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      ],
      banglaQuotes: [
        'আরো কিছু দিন ধৈর্য ধরো, নিশ্চয়ই আল্লাহ তোমাদের জন্য মুক্তির পথ তৈরি করবেন।',
        'আল্লাহ কোন ব্যক্তির উপর তার সাধ্যাতীত কোন দায়িত্ব চাপিয়ে দেন না।',
        'আরো কিছু দিন ধৈর্য ধরো, নিশ্চয়ই আল্লাহ তোমাদের জন্য মুক্তির পথ তৈরি করবেন।',
        'নিশ্চয়ই, আল্লাহ ধৈর্যশীলদের সাথে আছেন।',
        'কষ্টের পর সান্ত্বনা আছে।',
      ],
    ),
    Mood(
      id: 'anxious',
      name: 'Anxious',
      arabicName: 'قلق',
      icon: Icons.psychology,
      primaryColor: Color(0xFFFF9800),
      lightColor: Color(0xFFFFB74D),
      darkColor: Color(0xFFE65100),
      accentColor: Color(0xFFFFCC02),
      description: 'When worry consumes your thoughts',
      quotes: [
        'And whoever trusts in Allah, He will suffice him. Verily, Allah accomplishes His purpose.',
        'No anxiety or sorrow should afflict a Muslim without Allah expiating some of his sins.',
        'Remember Allah much, so that you may be successful.',
        'And Allah is predominant over His affair, but most of the people do not know.',
        'And upon Allah rely, if you should be believers.',
      ],
      arabicQuotes: [
        'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ',
        'لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
        'إِنَّمَا الْمُؤْمِنُونَ الَّذِينَ إِذَا ذُكِرَ اللَّهُ وَجِلَتْ قُلُوبُهُمْ',
        'وَتَوَكُّلْ عَلَى اللَّهِ إِن كُنتَ مُؤْمِنًا',
        'أَلَا إِنَّ نَصْرَ اللَّهِ قَرِيبٌ',
      ],
      banglaQuotes: [
        'যে আল্লাহর উপর ভরসা করে, আল্লাহ তাকে যথেষ্ট সাহায্য করেন।',
        'কোনো দুশ্চিন্তা বা দুঃখ মুসলিমকে স্পর্শ করলে আল্লাহ তার কিছু পাপ মাফ করে দেন।',
        'তোমরা আল্লাহকে অনেক স্মরণ করো, যাতে তোমরা সফল হতে পারো।',
        'আল্লাহ তাঁর কাজে প্রাধান্য দেন, কিন্তু বেশিরভাগ মানুষ জানে না।',
        'যদি তোমরা বিশ্বাসী হও, তবে আল্লাহর উপর ভরসা করো।',
      ],
    ),
    Mood(
      id: 'grateful',
      name: 'Grateful',
      arabicName: 'شاكر',
      icon: Icons.favorite,
      primaryColor: Color(0xFF2E7D32),
      lightColor: Color(0xFF4CAF50),
      darkColor: Color(0xFF1B5E20),
      accentColor: Color(0xFF66BB6A),
      description: 'When your heart overflows with gratitude',
      quotes: [
        'And whoever is grateful - he is grateful for [the benefit of] himself.',
        'If you are grateful, I will certainly give you more.',
        'And Allah has brought you out of the wombs of your mothers not knowing a thing, and He made for you hearing and vision and intellect that perhaps you would be grateful.',
        'And it is Allah who created you and will take you in death. And among you is he who is reversed to the most decrepit [old] age.',
        'So remember the favors of Allah that you might succeed.',
      ],
      arabicQuotes: [
        'وَمَن شَكَرَ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِ',
        'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
        'وَاللَّهُ أَخْرَجَكُم مِّن بُطُونِ أُمَّهَاتِكُمْ لَا تَعْلَمُونَ شَيْئًا وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ لَعَلَّكُمْ تَشْكُرُونَ',
        'وَاللَّهُ خَلَقَكُمْ ثُمَّ يَتَوَفَّاكُمْ ۚ وَمِنكُم مَّن يُرَدُّ إِلَىٰ أَرْذَلِ الْعُمُرِ',
        'فَاذْكُرُوا آلَاءَ اللَّهِ لَعَلَّكُمْ تُفْلِحُونَ',
      ],
      banglaQuotes: [
        'যে কৃতজ্ঞতা প্রকাশ করে, সে নিজের জন্যই কৃতজ্ঞতা প্রকাশ করে।',
        'যদি তোমরা কৃতজ্ঞতা প্রকাশ কর, আমি অবশ্যই তোমাদের আরো দেব।',
        'আল্লাহ তোমাদের মায়েদের গর্ভ থেকে বের করেছেন এমন অবস্থায় যে তোমরা কিছুই জানতে না এবং তিনি তোমাদের দিয়েছেন শ্রবণশক্তি, দৃষ্টিশক্তি ও হৃদয় যাতে তোমরা কৃতজ্ঞতা প্রকাশ কর।',
        'আল্লাহ তোমাদের সৃষ্টি করেছেন, অতঃপর তোমাদের মৃত্যু দেবেন। তোমাদের মধ্যে কেউ কেউ অতি বার্ধক্যে পৌঁছে।',
        'সুতরাং আল্লাহর নিয়ামতসমূহ স্মরণ কর যাতে তোমরা সফল হতে পার।',
      ],
    ),
    Mood(
      id: 'hopeful',
      name: 'Hopeful',
      arabicName: 'متفائل',
      icon: Icons.wb_sunny,
      primaryColor: Color(0xFFFBC02D),
      lightColor: Color(0xFFFFEB3B),
      darkColor: Color(0xFFF57F17),
      accentColor: Color(0xFFFFD54F),
      description: 'When hope lights your path',
      quotes: [
        'So verily, with the hardship, there is relief. Verily, with the hardship, there is relief.',
        'And Allah is the best of planners.',
        'My mercy encompasses all things.',
        'And whoever relies upon Allah - then He is sufficient for him.',
        'Do not lose hope, nor be sad.',
      ],
      arabicQuotes: [
        'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
        'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
        'وَاللَّهُ خَيْرُ الْمَاكِرِينَ',
        'رَبَّنَا وَآتِنَا مَا وَعَدْتَّنَا عَلَى رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ ۖ إِنَّكَ لَا تُخْلِفُ الْمِيعَادَ',
        'لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
      ],
      banglaQuotes: [
        'অতএব, নিশ্চয়ই, কষ্টের সাথে রয়েছে সুখ।',
        'আল্লাহ সেরা পরিকল্পনাকারী।',
        'আমার রহমত সবকিছুকে পরিবেষ্টন করে আছে।',
        'যে আল্লাহর উপর ভরসা করে, আল্লাহ তাকে যথেষ্ট সাহায্য করেন।',
        'নিরাশ হবেন না, দুঃখিত হবেন না।',
      ],
    ),
    Mood(
      id: 'peaceful',
      name: 'Peaceful',
      arabicName: 'مطمئن',
      icon: Icons.spa,
      primaryColor: Color(0xFF00796B),
      lightColor: Color(0xFF26A69A),
      darkColor: Color(0xFF004D40),
      accentColor: Color(0xFF4DB6AC),
      description: 'When serenity fills your heart',
      quotes: [
        'Those who believe and whose hearts find rest in the remembrance of Allah. Verily, in the remembrance of Allah do hearts find rest.',
        'And Allah invites to the Home of Peace and guides whom He wills to a straight path.',
        'Peace be upon you for what you patiently endured. And excellent is the final home.',
        'And Allah is the Hearing, the Knowing.',
        'Enter it in peace, secure.',
      ],
      arabicQuotes: [
        'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
        'اللَّهُ يَسْتَجِيبُ مَن دَعَاهُ',
        'إِنَّ الْمُتَّقِينَ فِي جَنَّاتٍ وَنَهَرٍ',
        'ادْخُلُوهَا بِسَلَامٍ آمِنِينَ',
        'وَقَالَتْ لَهُمْ خَزَنَتُهَا سَلَامٌ عَلَيْكُمْ طِبْتُمْ فَادْخُلُوهَا خَالِدِينَ',
      ],
      banglaQuotes: [
        'যারা বিশ্বাস করে এবং আল্লাহর স্মরণে তাদের হৃদয় শান্তি পায়। নিশ্চয়ই, আল্লাহর স্মরণে হৃদয় শান্তি পায়।',
        'আল্লাহ শান্তির গৃহে ডাকেন এবং যাকে ইচ্ছা তাকে সোজা পথে পরিচালিত করেন।',
        'তোমরা যে কারণে ধৈর্য ধরেছো, তার জন্য তোমাদের প্রতি শান্তি বর্ষিত হোক। এবং চূড়ান্ত গন্তব্য কত সুন্দর।',
        'আল্লাহ সবকিছু শোনেন, জানেন।',
        'সেখানে শান্তিতে প্রবেশ করো, নিরাপদে।',
      ],
    ),
    Mood(
      id: 'confused',
      name: 'Confused',
      arabicName: 'حائر',
      icon: Icons.help_outline,
      primaryColor: Color(0xFF7B1FA2),
      lightColor: Color(0xFF9C27B0),
      darkColor: Color(0xFF4A148C),
      accentColor: Color(0xFFBA68C8),
      description: 'When you seek clarity',
      quotes: [
        'And whoever fears Allah - He will make for him of his matter ease.',
        'And consult them in the matter. Then when you have taken a decision, trust in Allah.',
        'Allah is the light of the heavens and the earth.',
        'And Allah guides whom He wills to a straight path.',
        'Ask Allah for guidance in all your affairs.',
      ],
      arabicQuotes: [
        'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا',
        'وَشَاوِرْهُمْ فِي الْأَمْرِ فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ',
        'اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ',
        'وَاللَّهُ يَهْدِي مَن يَشَاءُ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ',
        'اللَّهُمَّ ارْشِدْنِي فِي أَمْرِي كُلِّهِ',
      ],
      banglaQuotes: [
        'যে আল্লাহকে ভয় করে, আল্লাহ তার কাজ সহজ করে দেন।',
        'তাদের সাথে পরামর্শ করো। তারপর যখন তুমি একটি সিদ্ধান্ত নিয়ে ফেলবে, আল্লাহর উপর ভরসা করো।',
        'আল্লাহ আকাশ ও পৃথিবীর আলো।',
        'আল্লাহ যাকে ইচ্ছা তাকে সোজা পথে পরিচালিত করেন।',
        'হে আল্লাহ, আমার সব কাজে আমাকে পথ দেখাও।',
      ],
    ),
    Mood(
      id: 'lonely',
      name: 'Lonely',
      arabicName: 'وحيد',
      icon: Icons.person_outline,
      primaryColor: Color(0xFF5D4037),
      lightColor: Color(0xFF8D6E63),
      darkColor: Color(0xFF3E2723),
      accentColor: Color(0xFFBCAAA4),
      description: 'When you feel isolated',
      quotes: [
        'And He is with you wherever you are.',
        'Allah is closer to you than your jugular vein.',
        'Remember Me; I will remember you.',
        'And Allah is the best companion.',
        'Indeed, Allah is with the patient.',
      ],
      arabicQuotes: [
        'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
        'وَأَن تَحْسَبُوهُ شَرًّا لَكُمْ بَلْ هُوَ خَيْرٌ لَّكُمْ',
        'وَاذْكُرُوا إِذْ أَنتُمْ قَلِيلٌ مُستَضَعَفُونَ فِي الْأَرْضِ',
        'اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا',
        'أَلَا إِنَّ نَصْرَ اللَّهِ قَرِيبٌ',
      ],
      banglaQuotes: [
        'তিনি তোমাদের সাথে আছেন যেখানে তোমরা থাকো।',
        'আল্লাহ তোমাদের গলার শিরার চেয়েও নিকটবর্তী।',
        'তোমরা আমাকে স্মরণ করো, আমি তোমাদের স্মরণ করবো।',
        'আল্লাহ সর্বশ্রেষ্ঠ সঙ্গী।',
        'নিশ্চয়ই, আল্লাহ ধৈর্যশীলদের সাথে আছেন।',
      ],
    ),
    Mood(
      id: 'stressed',
      name: 'Stressed',
      arabicName: 'متوتر',
      icon: Icons.speed,
      primaryColor: Color(0xFFE91E63),
      lightColor: Color(0xFFF48FB1),
      darkColor: Color(0xAD1457),
      accentColor: Color(0xFFEC407A),
      description: 'When pressure overwhelms you',
      quotes: [
        'And whoever relies upon Allah - then He is sufficient for him.',
        'Allah does not burden a soul beyond that it can bear.',
        'And whoever fears Allah - He will make for him of his matter ease.',
        'So remember Me; I will remember you.',
        'Pray to Allah and He will answer your call.',
      ],
      arabicQuotes: [
        'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ',
        'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
        'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا',
        'فَاذْكُرُوا اللَّهَ يَذْكُرْكُمْ',
        'ادْعُوا اللَّهَ وَيَسْتَجِبْ لَكُمْ',
      ],
      banglaQuotes: [
        'যে আল্লাহর উপর ভরসা করে, আল্লাহ তাকে যথেষ্ট সাহায্য করেন।',
        'আল্লাহ কোন ব্যক্তির উপর তার সাধ্যাতীত কোন দায়িত্ব চাপিয়ে দেন না।',
        'আরো কিছু দিন ধৈর্য ধরো, নিশ্চয়ই আল্লাহ তোমাদের জন্য মুক্তির পথ তৈরি করবেন।',
        'তোমরা আল্লাহকে অনেক স্মরণ করো, যাতে তোমরা সফল হতে পারো।',
        'আল্লাহর কাছে প্রার্থনা করো, তিনি তোমাদের ডাক শুনবেন।',
      ],
    ),
    Mood(
      id: 'tired',
      name: 'Tired',
      arabicName: 'متعب',
      icon: Icons.bedtime,
      primaryColor: Color(0xFF607D8B),
      lightColor: Color(0xFF90A4AE),
      darkColor: Color(0xFF37474F),
      accentColor: Color(0xFF78909C),
      description: 'When exhaustion weighs you down',
      quotes: [
        'And Allah will not make your faith of no effect.',
        'Rest is a blessing from Allah.',
        'And it is He who created the night and day.',
        'Come to prayer, come to success.',
        'Indeed, in the remembrance of Allah do hearts find rest.',
      ],
      arabicQuotes: [
        'وَلَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
        'النَّوْمُ أَخُو الْمَوْتِ',
        'وَجَعَلْنَا اللَّيْلَ لِبَاسًا',
        'وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ',
        'إِنَّ فِي ذَٰلِكَ لَذِكْرَى لِمَن كَانَ لَهُ قَلْبٌ أَوْ أَلْقَى السَّمْعَ وَهُوَ شَهِيدٌ',
      ],
      banglaQuotes: [
        'আল্লাহ তোমাদের ঈমানকে ব্যর্থ করবেন না।',
        'বিশ্রাম আল্লাহর একটি আশীর্বাদ।',
        'তিনি রাত ও দিনকে সৃষ্টি করেছেন।',
        'নামাজের দিকে এসো, সফলতার দিকে এসো।',
        'নিশ্চয়ই, আল্লাহর স্মরণে হৃদয় শান্তি পায়।',
      ],
    ),
    Mood(
      id: 'excited',
      name: 'Excited',
      arabicName: 'متحمس',
      icon: Icons.celebration,
      primaryColor: Color(0xFFFF5722),
      lightColor: Color(0xFFFF8A65),
      darkColor: Color(0xFFD84315),
      accentColor: Color(0xFFFF7043),
      description: 'When joy fills your being',
      quotes: [
        'And it is He who created you and will take you in death. And among you is he who is reversed to the most decrepit [old] age.',
        'So which of the favors of your Lord would you deny?',
        'Praise be to Allah, Lord of the worlds.',
        'And Allah has favor upon the believers.',
        'Say: In the bounty of Allah and in His mercy - in that let them rejoice.',
      ],
      arabicQuotes: [
        'وَاللَّهُ أَخْرَجَكُم مِّن بُطُونِ أُمَّهَاتِكُمْ لَا تَعْلَمُونَ شَيْئًا',
        'فَاذْكُرُوا آلَاءَ اللَّهِ لَعَلَّكُمْ تُفْلِحُونَ',
        'وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ',
        'إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ',
        'تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ',
      ],
      banglaQuotes: [
        'তিনি তোমাদের সৃষ্টি করেছেন, অতঃপর তোমাদের মৃত্যু দেবেন। তোমাদের মধ্যে কেউ কেউ অতি বার্ধক্যে পৌঁছে।',
        'সুতরাং আল্লাহর নিয়ামতসমূহ স্মরণ কর যাতে তোমরা সফল হতে পার।',
        'আল্লাহ সৎকর্মশীলদের ভালোবাসেন।',
        'যাদের নিচ দিয়ে নদী প্রবাহিত হয়।',
      ],
    ),
  ];

  static Mood getMoodById(String id) {
    return allMoods.firstWhere(
      (mood) => mood.id == id,
      orElse: () => allMoods.first,
    );
  }
}
